# ADVERSE - root delegating Makefile
#
# The project lives in adverse-go/. This wrapper keeps `make` at the
# repository root ergonomic while avoiding a second source of truth.
#
# Usage:
#   make build      # Linux binaries  → adverse-go/bin/
#   make windows    # Lab agent      → adverse-go/bin/registryfil.exe
#   make test       # go vet + go test
#   make lint       # go vet
#   make clean      # remove build outputs
#   make help       # this message
#
# Deployable Windows stubs (embedded config) are generated by the operator
# binary, not by make: `adversed gen-stub --help`.

.PHONY: build hardened obfuscated windows windows-hardened polymorph generate test test-race lint clean help

build:
	$(MAKE) -C adverse-go build

hardened:
	$(MAKE) -C adverse-go hardened

obfuscated:
	$(MAKE) -C adverse-go obfuscated

windows:
	$(MAKE) -C adverse-go windows

windows-hardened:
	$(MAKE) -C adverse-go windows-hardened

polymorph:
	$(MAKE) -C adverse-go polymorph

generate:
	$(MAKE) -C adverse-go generate

test:
	$(MAKE) -C adverse-go test

test-race:
	$(MAKE) -C adverse-go test-race

lint:
	$(MAKE) -C adverse-go lint

clean:
	$(MAKE) -C adverse-go clean

help:
	@echo "Targets:"
	@echo "  build              Build adversed (operator) + registryfil (lab agent) to adverse-go/bin/"
	@echo "  hardened           Hardened build: BuildID scrub, PIE, polymorphic seed, overlay-ready"
	@echo "  obfuscated         Full garble: literals + tiny + debug (hash/address obfuscation)"
	@echo "  windows            Lab agent: cross-compile registryfil.exe (GOOS=windows GOARCH=amd64)"
	@echo "  windows-hardened   Lab agent: Windows hardened cross-compile"
	@echo "  polymorph          Append random overlay to bust VT file-hash"
	@echo "  test               go vet + go test ./... (from adverse-go/)"
	@echo "  test-race          go vet + go test -race ./... (from adverse-go/)"
	@echo "  lint               go vet ./..."
	@echo "  clean              Remove adverse-go/bin/"
	@echo ""
	@echo "Generated Windows stubs (embedded config, no agent.json) come from:"
	@echo "  adversed gen-stub --secret-file <f> --server-url <url> --out stub.exe"
