// Command stringcrypt reads string_manifest.json and generates
// internal/obfuscate/stringtable_gen.go containing a compile-time encrypted
// string table. Plaintext strings never appear in the compiled binary.
//
// Usage:
//
//	go run ./tools/stringcrypt --seed 0xDE
//	POLY_SEED=deadbeef go run ./tools/stringcrypt
//
// The default seed (0xDE) matches the committed stringtable_gen.go, so a bare
// run with no seed regenerates the file byte-for-byte. The seed is written
// into the generated file next to the ciphertext; runtime decryption uses that
// embedded genStringSeed and never an ldflags override.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"hash/fnv"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// manifestEntry is a single {name, value} pair from the JSON manifest.
type manifestEntry struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// fnv1a32 computes FNV-1a 32-bit hash of s.
func fnv1a32(s string) uint32 {
	h := fnv.New32a()
	h.Write([]byte(s))
	return h.Sum32()
}

// rotatingXOR encrypts in with the given seed using the hardened schedule that
// matches obfuscate.RotatingXOR.  This is intentionally duplicated so the
// generator has zero dependency on the obfuscate package.
//
// Hardening: adds secondary key derivation and data-dependent feedback so the
// generated string table is encrypted with the same hardened schedule used at
// runtime.  Two seeds that happen to produce identical primary keystreams will
// diverge because the secondary key perturbs the initial state, and the
// ciphertext byte feeds back into the keystream.
func rotatingXOR(in []byte, seed byte) []byte {
	// Derive secondary key from primary seed (must match obfuscate.deriveSecondaryKey).
	sec := func(s byte) byte {
		k := uint16(s)
		k = (k * 0x9E37) & 0xFF
		k = (k << 3) | (k >> 5)
		return byte(k ^ 0xC5)
	}(seed)
	out := make([]byte, len(in))
	k := seed ^ sec
	for i, c := range in {
		out[i] = c ^ k
		k = (k ^ 0x55 ^ byte(i*0x13) ^ byte(i>>3) ^ out[i])
		if k == 0 {
			k = 0x5A
		}
	}
	return out
}

// goIdent turns a logical name like "NtdllDLL" into a Go constant name "StrNtdllDLL".
func goIdent(name string) string {
	return "Str" + name
}

// escapeByteLit formats a byte slice as a Go []byte literal.
func escapeByteLit(b []byte) string {
	var sb strings.Builder
	sb.WriteString("[]byte{")
	for i, v := range b {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "0x%02x", v)
	}
	sb.WriteString("}")
	return sb.String()
}

func main() {
	seedFlag := flag.String("seed", "", "hex seed byte (e.g. 0xDE). Falls back to POLY_SEED env, then default 0xDE.")
	flag.Parse()

	seed := byte(0xDE) // default matches the committed table so bare runs are idempotent

	// Honor POLY_SEED env if set (first 2 hex chars = 1 byte).
	if envSeed := os.Getenv("POLY_SEED"); envSeed != "" {
		if parsed, ok := parseHexByte(envSeed); ok {
			seed = parsed
		}
	}

	// Command-line flag overrides env.
	if *seedFlag != "" {
		if parsed, ok := parseHexByte(*seedFlag); ok {
			seed = parsed
		}
	}

	// Locate module root by walking up from cwd looking for go.mod.
	wd, _ := os.Getwd()
	modRoot := findModuleRoot(wd)
	if modRoot == "" {
		fmt.Fprintf(os.Stderr, "error: cannot locate go.mod from %s\n", wd)
		os.Exit(1)
	}

	manifestPath := filepath.Join(modRoot, "internal", "obfuscate", "string_manifest.json")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot find string_manifest.json at %s: %v\n", manifestPath, err)
		os.Exit(1)
	}

	var entries []manifestEntry
	if err := json.Unmarshal(data, &entries); err != nil {
		fmt.Fprintf(os.Stderr, "error: invalid manifest JSON: %v\n", err)
		os.Exit(1)
	}

	// Sort by name for deterministic output.
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	// Build the generated file.
	var sb strings.Builder
	sb.WriteString("// Code generated by tools/stringcrypt; DO NOT EDIT.\n\n")
	sb.WriteString("package obfuscate\n\n")
	sb.WriteString(fmt.Sprintf("// genStringSeed is the byte seed used to encrypt this table.\n// It is embedded here so runtime decryption always matches the committed generated file.\nvar genStringSeed byte = 0x%02x\n\n", seed))

	// const block
	sb.WriteString("const (\n")
	for _, e := range entries {
		id := fnv1a32(e.Name)
		sb.WriteString(fmt.Sprintf("\t%s uint32 = 0x%08x\n", goIdent(e.Name), id))
	}
	sb.WriteString(")\n\n")

	// genStringTable map
	sb.WriteString("// genStringTable maps each string ID to its RotatingXOR-encrypted ciphertext.\n// Decryption uses genStringSeed (embedded above). Plaintext never appears in .rodata.\n")
	sb.WriteString("var genStringTable = map[uint32][]byte{\n")
	for _, e := range entries {
		id := fnv1a32(e.Name)
		ct := rotatingXOR([]byte(e.Value), seed)
		sb.WriteString(fmt.Sprintf("\t0x%08x: %s,\n", id, escapeByteLit(ct)))
	}
	sb.WriteString("}\n")

	// Write to internal/obfuscate/stringtable_gen.go, gofmt-formatted so a
	// regeneration is byte-stable against gofmt'd checkouts.
	outPath := filepath.Join(modRoot, "internal", "obfuscate", "stringtable_gen.go")
	src, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: format generated source: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("generated %s (%d entries, seed=0x%02x)\n", outPath, len(entries), seed)
}

// findModuleRoot walks up from dir looking for go.mod.
func findModuleRoot(dir string) string {
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// parseHexByte parses the first 1-2 hex characters from a string as a byte.
func parseHexByte(s string) (byte, bool) {
	// Strip optional 0x/0X prefix.
	s = strings.TrimPrefix(s, "0x")
	s = strings.TrimPrefix(s, "0X")
	if len(s) < 1 {
		return 0, false
	}
	// Take up to 2 hex chars (1 byte).
	if len(s) > 2 {
		s = s[:2]
	}
	var val byte
	for _, c := range s {
		val <<= 4
		switch {
		case c >= '0' && c <= '9':
			val |= byte(c - '0')
		case c >= 'a' && c <= 'f':
			val |= byte(c - 'a' + 10)
		case c >= 'A' && c <= 'F':
			val |= byte(c - 'A' + 10)
		default:
			return 0, false
		}
	}
	return val, true
}
